# Generated by Django 5.1.1 on 2024-10-25 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_amount', models.FloatField()),
                ('time_horizon', models.IntegerField()),
                ('stock_tickers', models.CharField(max_length=255)),
                ('stock_percentages', models.CharField(max_length=255)),
                ('expected_return', models.FloatField()),
                ('expected_volatility', models.FloatField()),
                ('sharpe_ratio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimized_weights', models.JSONField()),
                ('expected_return', models.FloatField()),
                ('expected_volatility', models.FloatField()),
                ('sharpe_ratio', models.FloatField()),
                ('allocation', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='OptimizationResult',
        ),
    ]
