# Generated by Django 5.1.1 on 2024-10-25 20:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_optimizationreport_portfoliooptimization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
